A small batch of updates
allan-simon/py-imap-to-http pull request #3
Opened 2020-02-18 09:18 UTC by Ramblurr

Loving this project. It was exactly what I needed to build [nextcloud-filedrop](https://github.com/Ramblurr/nextcloud-filedrop).

Here's a small batch of updates:

* We throw an error now when authentication fails, the error message otherwise is obscure and not obvious
* For development purposes I like to use a `.env` file rather than export the vars into my shell session. So I added `python-dotenv` as an optional dependency. If it exists the env vars will be populated from `.env`.
* Added a new field to the POST request: `date` from the date header of the email
* The Dockerfile was broken. The tagged base image doesn't exist anymore. I changed it to pin to `3.8-slim`

2020-02-18 10:35 UTC, allan-simon requested changes
thanks a lot for your MR and happy to learn it's useful to you :)

2020-02-18 10:35 UTC, allan-simon commented on service/__main__.py
> +    load_dotenv()
i'm more used to doing a try catch ImportError, I think it's more pythonic (ask for forgiveness, not permission)

2020-02-18 10:35 UTC, allan-simon commented on service/__main__.py
> +    r = yield from imap_client.login(user, password)
r => result ?

2020-10-13 07:23 UTC, Ramblurr commented
@allan-simon getting back round to this, sorry for the super long delay... things came up.

I've addressed your feedback!

2020-10-13 07:58 UTC, merged